// Generated by CoffeeScript 1.7.1
angular.module('rc.configs', []);

angular.module('rc.services', []);

angular.module('rc.controllers', []);

angular.module('rc.directives', []);

angular.module('rc.filters', []);

angular.module('underscore', []).factory('_', function() {
  return window._;
});

angular.module('D3', []).factory('d3', function() {
  return window.d3;
});

angular.module('rcApp', ['rc.configs', 'rc.services', 'rc.controllers', 'rc.directives', 'rc.filters', 'underscore', 'D3', 'ui.router'])
	.config(['$stateProvider', '$urlRouterProvider',function ($stateProvider, $urlRouterProvider) {
		$urlRouterProvider.otherwise('/');
		$stateProvider.
			state('login',{
				url: '/',
				templateUrl:'views/login.html',
				controller: 'LoginController'
			}).
			state('dashboard', {
				url: '/dashboard',
				templateUrl: 'views/dashboard.html',
				controller: 'mainCtrl'
			})

	}])
